name: Deploy Docker App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Подключаемся к серверу через SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ SECRET_FOR_TG_BOT.SERVER_HOST }}
          username: ${{ SECRET_FOR_TG_BOT.SERVER_USERNAME }}
          password: ${{ SECRET_FOR_TG_BOT.SERVER_PASSWORD }}  # Используйте SSH-ключ для безопасности
          port: 22
          debug: true  # Включает отладку
          script: |
            cd /home/grandhouse/telegram_bot  # Путь к вашему проекту на сервере
            git pull origin main      # Обновляем код с GitHub
            docker build -t tg-bot .  # Собираем Docker-образ локально на сервере
            docker stop tg-bot || true
            docker rm tg-bot || true
            docker run -d --name tg-bot -p 3000:3000 --env-file /home/grandhouse/telegram_bot/.env tg-bot
